services:
  postgres:
    image: postgres:16
    container_name: LowFareAirDB
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: OtworSpecjalista666
      POSTGRES_USER: postgres
      POSTGRES_DB: lowfareair
    ports:
      - "7004:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: